version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    command: npm run dev
    ports:
      - '21971:21971'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=development_password
      - DB_DATABASE=tgeld
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development_password
      - POSTGRES_DB=tgeld
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data_dev:
    driver: local
