# Production configuration for tgeld
# Single container with Next.js, PostgreSQL, and Prisma
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '21971:21971'  # Next.js
      - '5432:5432'    # PostgreSQL (optional, comment out if not needed)
    volumes:
      - uploads:/app/uploads
      - db:/var/lib/postgresql/data
    environment:
      # Production environment variables
      - NODE_ENV=production
      - NEXT_PUBLIC_PORT=21971
      # Database configuration (internal)
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-tgeld_secure_password_2024}
      - DB_DATABASE=tgeld
      # Prisma database URL
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-tgeld_secure_password_2024}@localhost:5432/tgeld?schema=public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && wget --spider http://localhost:21971/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
  db:
